plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.kover)
}

android {
    namespace = "com.mtschoen.windowstream.viewer"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.mtschoen.windowstream.viewer"
        minSdk = 34
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    // Two flavors: `portable` runs on Quest / phones / tablets / Galaxy XR as
    // a plain 2D window (no Jetpack XR at runtime). `gxr` keeps the v1
    // immersive panel experience for Samsung Galaxy XR. Both flavors share
    // src/main/; only the LAUNCHER activity and xr.immersive feature
    // declaration differ (see flavor-specific AndroidManifest.xml files).
    flavorDimensions += "target"
    productFlavors {
        create("portable") {
            dimension = "target"
        }
        create("gxr") {
            dimension = "target"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
    }
    testOptions {
        unitTests.all { it.useJUnitPlatform() }
        managedDevices {
            devices {
                create<com.android.build.api.dsl.ManagedVirtualDevice>("pixel6api36") {
                    device = "Pixel 6"
                    apiLevel = 36
                    systemImageSource = "google"
                }
            }
        }
    }
    sourceSets["androidTest"].assets.srcDirs("src/androidTest/assets")
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.xr.scenecore)
    implementation(libs.androidx.xr.compose)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.serialization.json)

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.mockk)

    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.kotlinx.coroutines.test)
}

// Copies the pre-recorded H.264 sample from testdata/ into the androidTest assets directory
// so it is available on the device at runtime. Run `pwsh testdata/generate-sample-h264.ps1`
// to regenerate testdata/sample-h264.bin before building if the file is missing.
// The copy is skipped if the source file does not exist (e.g. on a fresh checkout before
// running the generator script).
val copySampleH264 by tasks.registering(Copy::class) {
    val sourceFile = rootProject.file("testdata/sample-h264.bin")
    onlyIf { sourceFile.exists() }
    from(sourceFile)
    into("src/androidTest/assets")
}
tasks.named("preBuild").configure { dependsOn(copySampleH264) }

kover {
    // Use JaCoCo as the coverage engine. JaCoCo correctly excludes synthetic
    // bytecode branches (e.g. checkcast exception paths) generated by the
    // kotlinx-serialization compiler plugin, which the default IntelliJ engine
    // would count as uncoverable branches.
    useJacoco()
    reports {
        filters {
            excludes {
                // Lifecycle entry points are not unit-testable on the JVM.
                // ServerSelectionActivity (portable flavor) is the launcher
                // activity for non-XR devices; it drives mDNS discovery and
                // hands off to DemoActivity on server pick. Same rationale as
                // MainActivity — Android lifecycle classes require the
                // emulator / device runtime and are covered by manual /
                // integration testing.
                classes(
                    "com.mtschoen.windowstream.viewer.app.WindowStreamViewerApplication",
                    "com.mtschoen.windowstream.viewer.app.MainActivity",
                    "com.mtschoen.windowstream.viewer.app.MainActivity\$*",
                    "com.mtschoen.windowstream.viewer.app.ServerSelectionActivity",
                    "com.mtschoen.windowstream.viewer.app.ServerSelectionActivity\$*"
                )
                // Compose UI composables require the Android Compose runtime and cannot
                // be unit-tested on the JVM. ServerPickerScreen and ConnectedPanelScreen
                // are thin wrappers over discovered-server state and XR scene composition;
                // their correctness is verified by manual/emulator testing in Phase 13.
                // MultiServerPickerScreen (portable flavor) drives the multi-window pick
                // flow for Quest/phone/tablet — pure Compose state-management over a
                // SharedFlow of discovered servers, same rationale as ServerPickerScreen.
                classes(
                    "com.mtschoen.windowstream.viewer.app.ui.ServerPickerScreenKt",
                    "com.mtschoen.windowstream.viewer.app.ui.ServerPickerScreenKt\$*",
                    "com.mtschoen.windowstream.viewer.app.ui.ConnectedPanelScreenKt",
                    "com.mtschoen.windowstream.viewer.app.ui.ConnectedPanelScreenKt\$*",
                    "com.mtschoen.windowstream.viewer.app.ui.MultiServerPickerScreenKt",
                    "com.mtschoen.windowstream.viewer.app.ui.MultiServerPickerScreenKt\$*"
                )
                // The kotlinx-serialization compiler plugin emits $$serializer singleton
                // objects and $Companion helper classes as infrastructure; they are not
                // user-authored logic and are not callable from production code.
                classes(
                    "com.mtschoen.windowstream.viewer.control.*\$\$serializer",
                    "com.mtschoen.windowstream.viewer.control.*\$Companion"
                )
                // NSD wrapper and its result type require Android runtime;
                // covered by Phase 13 integration test.
                classes(
                    "com.mtschoen.windowstream.viewer.discovery.NetworkServiceDiscoveryClient",
                    "com.mtschoen.windowstream.viewer.discovery.NetworkServiceDiscoveryClient\$*",
                    "com.mtschoen.windowstream.viewer.discovery.ServerInformation"
                )
                // The eviction coroutine uses the `while (isActive) { delay() }` pattern.
                // JaCoCo counts the while-false branch as missed because `delay()` always
                // throws CancellationException on cancellation, so the condition never
                // evaluates to false. This is an inherent, unreachable branch in the
                // Kotlin coroutine cooperative-cancellation idiom.
                classes(
                    "com.mtschoen.windowstream.viewer.transport.UdpTransportReceiver\$start\$1",
                    "com.mtschoen.windowstream.viewer.transport.UdpTransportReceiver\$start\$2"
                )
                // The Kotlin coroutines compiler plugin generates continuation state-machine
                // classes for local suspend functions. These inner classes contain synthetic
                // resume-path branches that are unreachable from test code.
                classes(
                    "com.mtschoen.windowstream.viewer.control.ControlClient\$connect\$2\$sendMessage\$2",
                    "com.mtschoen.windowstream.viewer.control.ControlConnection"
                )
                // MediaCodecDecoder requires Android's MediaCodec framework, which is not
                // available in the JVM unit-test environment. It is exercised by the Phase 23
                // end-to-end emulator test. Excluded here following the same pattern as
                // NetworkServiceDiscoveryClient (Phase 7).
                classes(
                    "com.mtschoen.windowstream.viewer.decoder.MediaCodecDecoder",
                    "com.mtschoen.windowstream.viewer.decoder.MediaCodecDecoder\$*"
                )
                // DemoActivity + DirectSurfaceFrameSink are Android lifecycle classes:
                // DemoActivity hosts a SurfaceView, dispatches keyboard events, and drives
                // the viewer pipeline. DirectSurfaceFrameSink wraps an Android Surface.
                // Both require the Android runtime. TEST-REPORT.md endorses excluding
                // these with the same rationale as MainActivity; tests are tracked there
                // as future work. ControlMessage.KeyEvent (the V2 keyboard relay message)
                // currently has no round-trip serialization test — also tracked in
                // TEST-REPORT.md; exclude until paired with ViewerReady round-trip tests.
                classes(
                    "com.mtschoen.windowstream.viewer.demo.DemoActivity",
                    "com.mtschoen.windowstream.viewer.demo.DemoActivity\$*",
                    "com.mtschoen.windowstream.viewer.demo.DirectSurfaceFrameSink",
                    "com.mtschoen.windowstream.viewer.control.ControlMessage\$KeyEvent"
                )
                // ViewerPipeline.Companion.create() constructs ControlClient,
                // UdpTransportReceiver, and MediaCodecDecoder — all three require Android
                // runtime or network sockets and cannot be called in JVM unit tests.
                // Tests construct ViewerPipeline directly via its all-parameters constructor,
                // injecting mock factories. The Companion object therefore remains uncalled
                // in the unit-test environment. The connect$2 class is the Kotlin-compiler-
                // generated continuation for the scope.launch block; it contains a synthetic
                // resume-path branch unreachable from tests, following the same pattern as
                // ControlClient$connect$2$sendMessage$2.
                classes(
                    "com.mtschoen.windowstream.viewer.app.ViewerPipeline\$Companion",
                    "com.mtschoen.windowstream.viewer.app.ViewerPipeline\$connect\$2",
                    "com.mtschoen.windowstream.viewer.app.ViewerPipeline\$beginStreaming\$1"
                )
                // WindowStreamScene is a Compose-for-XR composable that hosts a SpatialExternalSurface
                // panel entity. It requires the Jetpack XR runtime (android.xr.runtime) which is not
                // available in the JVM unit-test environment. The pure dimension-computation helper
                // (computePanelDimensionsMeters) is extracted as an internal function and is covered
                // by PanelDimensionsTest. The wildcard pattern captures the Kotlin compiler-generated
                // inner classes for the composable lambda bodies.
                classes(
                    "com.mtschoen.windowstream.viewer.xr.WindowStreamSceneKt",
                    "com.mtschoen.windowstream.viewer.xr.WindowStreamSceneKt\$*"
                )
            }
        }
        verify {
            rule {
                @Suppress("UnstableApiUsage")
                minBound(100, kotlinx.kover.gradle.plugin.dsl.CoverageUnit.LINE)
                @Suppress("UnstableApiUsage")
                minBound(100, kotlinx.kover.gradle.plugin.dsl.CoverageUnit.BRANCH)
            }
        }
    }
}
