plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.kover)
}

android {
    namespace = "com.mtschoen.windowstream.viewer"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.mtschoen.windowstream.viewer"
        minSdk = 34
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
    }
    testOptions {
        unitTests.all { it.useJUnitPlatform() }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.xr.scenecore)
    implementation(libs.androidx.xr.compose)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.serialization.json)

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.mockk)

    androidTestImplementation(libs.junit.jupiter)
    androidTestImplementation(libs.kotlinx.coroutines.test)
}

kover {
    // Use JaCoCo as the coverage engine. JaCoCo correctly excludes synthetic
    // bytecode branches (e.g. checkcast exception paths) generated by the
    // kotlinx-serialization compiler plugin, which the default IntelliJ engine
    // would count as uncoverable branches.
    useJacoco()
    reports {
        filters {
            excludes {
                // Lifecycle entry points are not unit-testable on the JVM.
                classes(
                    "com.mtschoen.windowstream.viewer.app.WindowStreamViewerApplication",
                    "com.mtschoen.windowstream.viewer.app.MainActivity"
                )
                // The kotlinx-serialization compiler plugin emits $$serializer singleton
                // objects and $Companion helper classes as infrastructure; they are not
                // user-authored logic and are not callable from production code.
                classes(
                    "com.mtschoen.windowstream.viewer.control.*\$\$serializer",
                    "com.mtschoen.windowstream.viewer.control.*\$Companion"
                )
                // NSD wrapper and its result type require Android runtime;
                // covered by Phase 13 integration test.
                classes(
                    "com.mtschoen.windowstream.viewer.discovery.NetworkServiceDiscoveryClient",
                    "com.mtschoen.windowstream.viewer.discovery.NetworkServiceDiscoveryClient\$*",
                    "com.mtschoen.windowstream.viewer.discovery.ServerInformation"
                )
                // The eviction coroutine uses the `while (isActive) { delay() }` pattern.
                // JaCoCo counts the while-false branch as missed because `delay()` always
                // throws CancellationException on cancellation, so the condition never
                // evaluates to false. This is an inherent, unreachable branch in the
                // Kotlin coroutine cooperative-cancellation idiom.
                classes(
                    "com.mtschoen.windowstream.viewer.transport.UdpTransportReceiver\$start\$1",
                    "com.mtschoen.windowstream.viewer.transport.UdpTransportReceiver\$start\$2"
                )
                // The Kotlin coroutines compiler plugin generates continuation state-machine
                // classes for local suspend functions. These inner classes contain synthetic
                // resume-path branches that are unreachable from test code.
                classes(
                    "com.mtschoen.windowstream.viewer.control.ControlClient\$connect\$2\$sendMessage\$2",
                    "com.mtschoen.windowstream.viewer.control.ControlConnection"
                )
                // WindowStreamScene is a Compose-for-XR composable that hosts a SpatialExternalSurface
                // panel entity. It requires the Jetpack XR runtime (android.xr.runtime) which is not
                // available in the JVM unit-test environment. The pure dimension-computation helper
                // (computePanelDimensionsMeters) is extracted as an internal function and is covered
                // by PanelDimensionsTest. The wildcard pattern captures the Kotlin compiler-generated
                // inner classes for the composable lambda bodies.
                classes(
                    "com.mtschoen.windowstream.viewer.xr.WindowStreamSceneKt",
                    "com.mtschoen.windowstream.viewer.xr.WindowStreamSceneKt\$*"
                )
            }
        }
        verify {
            rule {
                @Suppress("UnstableApiUsage")
                minBound(100, kotlinx.kover.gradle.plugin.dsl.CoverageUnit.LINE)
                @Suppress("UnstableApiUsage")
                minBound(100, kotlinx.kover.gradle.plugin.dsl.CoverageUnit.BRANCH)
            }
        }
    }
}
